CLIENT_ID: "AcSjNmUPlOUlKGhH_-RcitjEsI0tNvws-k51n42DP27GWKTtLTV6Myr9l-9YNSg4RVOXBVV9JGnxxWEc"
SECRET: "EFtK7gq8gYar6BwgiK4WEiXOGW33EkVkLP3nKqo_-17XUpFBfXia3nvchsgb8tKGDBBppZVX46cB8Iyi"

BRAND_NAME: "Your Server"

CATEGORY_MENU_TITLE: "&aCategories"
CATEGORY_MENU_ROWS: 3

CHECK_EVERY: 300 #How often to check pending transactions (in seconds) - Default: 5 minutes
EXPIRE_AFTER: 3600000 #When a pending transaction will be removed (in milliseconds) - Default: 1 hour

STORE_COMMAND:
  ENABLED: true
  MAIN_COMMAND: "store"
  ALIASES:
    - "shop"
    - "buy"

CANCEL_COMMAND:
  ENABLED: true
  MAIN_COMMAND: "cancelitem"
  ALIASES:
    - "cancel"
    - "canceltransaction"

TIMER_COMMAND:
  ENABLED: true
  MAIN_COMMAND: "timer"
  ALIASES:
    - "transactiontimer"
    - "expiration"

LOOKUP_COMMAND:
  ENABLED: true
  MAIN_COMMAND: "lookup"
  PENDING_MESSAGE: "{player}, {item}, {cost}, {expiry}"
  HISTORIC_MESSAGE: "{player}, {item}, {cost}, {created}, {captured}"
  ALIASES:
    - "transactionlookup"
    - "lookuporder"

CATEGORIES:
  ranks:
    POSITION: 12
    MATERIAL: "STONE"
    DISPLAY: "&cRanks"
    ROWS: 2
    LORE:
      - "test1"
      - "test2"

ITEMS:
  VIP:
    POSITION: 3
    PASS_FEE: true
    MATERIAL: "STONE"
    #Note: Display cannot be identical to any other item's display. Use a random color code in front of another to bypass.
    #Example: Good = "&f&cVIP" and "&cVIP" | Bad = "&cVIP" and "&cVIP"
    DISPLAY: "&cVIP"
    CATEGORY: "ranks"
    COST: 10
    COMMANDS:
      - "rank add {player} gay"
      - "bc {player} did gay"
    LORE:
      - "test1"
      - "test2"
  MVP:
    POSITION: 5
    PASS_FEE: true
    MATERIAL: "STONE"
    DISPLAY: "&4MVP"
    CATEGORY: "ranks"
    COST: 20
    COMMANDS:
      - "rank add {player} gay"
      - "bc {player} did gay"
    LORE:
      - "test1"
      - "test2"
